# 텐서(Tensor)
### 텐서 : 배열(array)와 행렬(matrix)과 유사한 자료구조
### Pytorch에서는 텐서를 이용하요 모델의 입력과 출력, 매개변수의 부호화를 한다.
### 텐서는 GPU나 다른 하드웨어 가속기에서 실행하는 점만 제외하면 numpy의 ndarray와 매우 유사하다. 
### - 자동미분에 최적화가 되어있다. 

In [1]:
import torch
import numpy as np

In [52]:
# 텐서 초기화 
# 1. 데이터로부터 직접 생성하기
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data, type(x_data)

(tensor([[1, 2],
         [3, 4]]),
 torch.Tensor)

In [4]:
# 자료형은 자동으로 유추합니다.

torch.Tensor

In [53]:
# 2. Numpy 배열로부터 생성
np_array = np.array(data)
x_np = torch.tensor(np_array)
x_np, type(x_np)

(tensor([[1, 2],
         [3, 4]], dtype=torch.int32),
 torch.Tensor)

In [6]:
type(x_np)

torch.Tensor

In [9]:
# 3. 무작위(random)와 상수(constant) 값을 사용
# shape는 텐서의 차원을 나타내는 튜플
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.7201, 0.8759, 0.7510],
         [0.5333, 0.2718, 0.5705]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [10]:
### 텐서의 속성 
# 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지 나타냄
tensor = torch.rand(3,4) 
tensor

tensor([[0.1333, 0.2686, 0.8532, 0.7953],
        [0.9186, 0.9008, 0.2792, 0.5218],
        [0.7256, 0.2703, 0.4026, 0.6121]])

In [11]:
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [54]:
### 텐서 연산
# 기본적으로 텐서는 CPU에 생성된다 -> .to 메서드를 사용하면 GPU 가용성을 확인한 뒤 GPU로 이동할 수 있다. 
# 장치들 간에 큰 텐서들을 복사하는 것은 메모리와 시간이 많이 든다는 것을 기억 해야한다.
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [13]:
# numpy 라이브러리에 익숙 하다면 tensor를 사용하기는 아주 쉽습니다. 
tensor = torch.ones(4,4)
print("Frist row : ", tensor[0])
print("First column : ", tensor[:, 0])
print("Last Colunm : ", tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

Frist row :  tensor([1., 1., 1., 1.])
First column :  tensor([1., 1., 1., 1.])
Last Colunm :  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
# 텐서 합치기 : torch.cat 
# 주어진 차원에 따라 텐서를 연결이 가능 
tensor = torch.cat([tensor, tensor, tensor], dim=1) # 가로 합치기
tensor

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [17]:
tensor = torch.ones(4,4) 
tensor = torch.stack([tensor, tensor, tensor], dim=1) # 세로 합치기 
tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [20]:
### 산술 연산 
# 두 텐서간의 행렬 곱 , y1, y2, y3는 다 같은 값이다.
tensor = torch.ones(4,4) 
y1 = tensor @ tensor.T
y1

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [21]:
y2 = tensor.matmul(tensor.T) # .T 는 역행렬 
y2

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [26]:
y3 = torch.rand_like(tensor)
y3

tensor([[0.6230, 0.6839, 0.6466, 0.2027],
        [0.3350, 0.8512, 0.9378, 0.6615],
        [0.9681, 0.2372, 0.5259, 0.7314],
        [0.7410, 0.9694, 0.4121, 0.6484]])

In [27]:
torch.matmul(tensor, tensor.T, out=y3)
y3

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [29]:
# 요소별 곱 계산 
z1 = tensor*tensor
z1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
z2 = tensor.mul(tensor)
z2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
z3 = torch.rand_like(tensor)
z3

tensor([[0.2030, 0.6912, 0.8390, 0.4405],
        [0.7670, 0.7544, 0.0211, 0.0521],
        [0.1104, 0.9401, 0.5529, 0.1126],
        [0.5895, 0.9016, 0.7845, 0.8932]])

In [36]:
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
# 단일요소 텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서인 경우 item()을 사용하여 숫자로 변환 가능
agg = tensor.sum()
agg

tensor(16.)

In [39]:
agg.item(), type(agg.item())

(16.0, float)

In [44]:
# 바꿔치기 연산 : 연산결과를 피연산자에 저장하는 연산 
# _ 접미사를 붙인다
tensor = torch.ones(4,4) 
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [45]:
tensor.add_(5)
tensor

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [48]:
# Numpy 변환
# cpu상 텐서와 numpy 배열은 메모리 공간 공유 -> 하나를 변경하면 다른 하나도 변경
# 텐서 -> numpy 배열 변경 
t = torch.ones(5)
n = t.numpy()
print(f"t : {t}")
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [49]:
t.add_(1)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


In [51]:
# numpy -> tensor
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
