In [2]:
import torch
import numpy as np

In [4]:
# 뷰(view) 원소의 수를 유지하면서 텐서의 크기 변경! 매우 중요 
# 파이토치 센서의 뷰는 numpy에서의 reshape 같은 역할을 한다. 
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
             [[6, 7, 8],
              [9, 10, 11]]])

ft = torch.FloatTensor(t)

In [5]:
print(ft.shape)

torch.Size([2, 2, 3])


In [7]:
# 4 - 1 3차원 텐서에서 2차원으로 변경 
# view([-1, 3])이 가지는 의미 : -1 : 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다는 의미 
# 3 : 두번째 차원의 길이는 3으로 하라는 의미 
# 즉, (?, 3)의 크기를 가지게 하는 것 
# 결국 내부적으로 (2,2,3) -> (?, 3) 의 형태로 된다.

# view 규칙 : 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야함 
# 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추 
print(ft.shape)  # 2 x 2 x 3 = 12
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape) # 4 x 3 = 12 

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [8]:
# 4 - 2 3차원 텐서의 크기 변경 
# 3차원 텐서에서 3차원 텐서로 차원은 유지하는데 shape를 바꾸는 작업 
# (2 x 2 x 3) = 12 와 ( ? x 1 x 3 ) = 12가 되기 위해 ?는 4가 되어야한다.

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [9]:
# 5) 스퀴즈(Squeeze) - 차원이 1인 것을 제거 
ft = torch.FloatTensor([[0], [1], [2]])

print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [10]:
# 원래 텐서는 ( 3 x 1 )을 가지지만 두번째 차원이 1이므로 squeeze를 사용하며 (3, )의 크기를 가지는 텐서로 변경
# 1차원 벡터가 되는 것이 보여짐 
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [11]:
# 6) 언스퀴즈 (unsqueeze) 특정 위치에 1인 차원을 추가

ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [12]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [13]:
# 2차원으로 바꾸고 싶으면서 첫번째 차원은 1이기를 원한다면 view에서 (1, -1)인자를 사용 
# 언퀴즈와 동일한 결과가 나온다 
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [14]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [15]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [16]:
# 결론 : view(), squeeze(), unsqueeze() 는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절

In [18]:
# 7) 타입 캐스팅(Type Casting)
# 텐서의 자료형을 변환 하는 것을 타입 캐스팅이라고 함

lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [20]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [21]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [22]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [23]:
# 8) 연결하기 (concatenate)
# 딥러닝에서는 주로 모델의 입력 또는 중간 연산에서 두 개의 텐서를 연결하는 경우가 많습니다. 
# 두 텐서를 연결해서 입력으로 사용하는 것은 두가지의 정보를 모두 사용한다는 의미
x = torch.FloatTensor([[1, 2], [3, 4]]) # ( 2 x 2 )
y = torch.FloatTensor([[5, 6], [7, 8]]) # ( 2 x 2 )

In [24]:
print(torch.cat([x,y], dim = 0)) # ( 4 x 2 )

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [25]:
print(torch.cat([x,y], dim = 1)) # ( 2 x 4 )

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [26]:
# 9) 스택킹(Stacking) 
# concat을 하는 다른 방법으로 stacking이 있다
# stacking은 영어로 쌓는다는 의미 

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [27]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [28]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim  = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [29]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [31]:
# 10 ) ones_like 와 zeros_like : 1과 0으로 채워진 텐서 

x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [32]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [35]:
# 11) In-place Operation (덮어쓰기 연산)

x = torch.FloatTensor([[1, 2], [3, 4]]) # (2 x 2) 
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [34]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [36]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
